<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MSM6650_Database_Decoder</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<SelfContained>true</SelfContained>
	<PublishSingleFile>true</PublishSingleFile>
	<Platforms>AnyCPU;x64</Platforms>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\wmast\.nuget\packages\naudio.lame\2.1.0\build\libmp3lame.32.dll" />
  </ItemGroup>

</Project>
